### ISSUE TITLE
Can't find ffmpeg library nor binary

### ISSUE THREAD

**Issue by LounaCodes** [psyGamer/TASRecorder#8]
I use Arch linux and have ffmpeg plus its dependencies installed properly vial pacman, however TASRecorder can't find it for some reason?
check the log here:
[log.txt](https://github.com/user-attachments/files/18270305/log_20241229_173700.txt)
I have hardware acceleration disabled, because it requires proprietary drivers, I don't have installed, but this has worked in the past.

**Enabled mods:**
CelesteTAS
TASRecorder
LowQualityGarbage (the map I wrote a TAS for)
BrokemaniaHelper
CommunalHelper
FlagelinesAndSuch
MaxHelpingHand
ShroomHelper
VivHelper

**System info:**
OS: Arch Linux x86_64
Kernel: Linux 6.12.6-zen1-1-zen
WM: Hyprland (Wayland)
CPU: AMD Ryzen 5 2600X (12) @ 3.60 GHz
GPU: AMD Radeon RX 6800 XT [Discrete]

**Comment by psyGamer** [comment]
Steam seems to be doing something weird causing binaries/libraries to not be found.
You can try putting a file called `steam_appid.txt` next to your `Celeste.dll`, with the contents `504230`. That should prevent Steam from relaunching through itself and hopefully fix it.

**Comment by LounaCodes** [comment]
Alright so It's been a while, but I'm running into the same issue. Adding steam_appid.txt helps and the mod detects both the library and binary, but when I try to record a TAS, I get this Error:
```
(08/17/2026 21:55:03) [Everest] [Error] [TASRecorder] FFmpeg binary process failed!
--------------------------------
System.AggregateException: One or more errors occurred. (Broken pipe)

--------------------------------
System.IO.IOException: Broken pipe
   at System.IO.Pipes.PipeStream.WriteAsyncCore(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
   at Celeste.Mod.TASRecorder.VideoPipeSource.WriteAsync(Stream stream, CancellationToken token) in /media/Storage/Games/Celeste_NETCore3/Mods/Capture/Source/Encoder/FFmpegBinaryEncoder.cs:line 30
   at FFMpegCore.Arguments.InputPipeArgument.ProcessDataAsync(CancellationToken token)
   at FFMpegCore.Arguments.PipeArgument.During(CancellationToken cancellationToken)
   at FFMpegCore.FFMpegArguments.During(CancellationToken cancellationToken)
   at FFMpegCore.FFMpegArgumentProcessor.Process(ProcessArguments processArguments, CancellationTokenSource cancellationTokenSource)
   at FFMpegCore.FFMpegArgumentProcessor.ProcessAsynchronously(Boolean throwOnError, FFOptions ffMpegOptions)
--------------------------------
System.Net.Sockets.SocketException: Broken pipe
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.IO.Pipes.PipeStream.WriteAsyncCore(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
```

**Comment by LounaCodes** [comment]
Ok, so I did get it to work by playing with the settings. The binary works fine with default setting, but using the library, I get this Error:
```
(08/17/2026 22:46:02) [Everest] [Error] [TASRecorder] Failed to start recording!
--------------------------------
System.NullReferenceException: Object reference not set to an instance of an object.
   at Celeste.Mod.TASRecorder.FFmpegLibraryEncoder.AddStream(AVCodec* codec, OutputStream& outStream, AVCodecID codecID) in /media/Storage/Games/Celeste_NETCore3/Mods/Capture/Source/Encoder/FFmpegLibraryEncoder.cs:line 226
   at Celeste.Mod.TASRecorder.FFmpegLibraryEncoder..ctor(String fileName) in /media/Storage/Games/Celeste_NETCore3/Mods/Capture/Source/Encoder/FFmpegLibraryEncoder.cs:line 88
   at Celeste.Mod.TASRecorder.RecordingManager.StartRecording(String fileName) in /media/Storage/Games/Celeste_NETCore3/Mods/Capture/Source/RecordingManager.cs:line 33
   at Celeste.Mod.TASRecorder.TASRecorderAPI.StartRecording(String fileName) in /media/Storage/Games/Celeste_NETCore3/Mods/Capture/Source/TASRecorderAPI.cs:line 2
```

**Comment by psyGamer** [comment]
I'm planning on reworking the shipped libraries to work anywhere, for real this time.
